version: '3'
services:

  proposta_api:
    build:
      dockerfile: dockerfile
      context: .
    image: raphaelfeitosa/proposta_api:1.0.0
    restart: on-failure
    container_name: proposta_api
    ports:
      - "8081:8081"
    depends_on:
      - proposta_api_db

  proposta_api_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: proposta_api_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=proposta_api_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume-proposta:/var/lib/mysql

volumes:
  mysql-volume-proposta: