server:
  port: 8081
spring:
  application:
    name: proposta_api
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# Datasource - MySQL
  datasource:
    url: jdbc:mysql://proposta_api_db:3306/proposta_api_db
    username: root
    password: password

# Key Cloack
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://keycloak:8080/auth/realms/proposta
        jwk-set-uri: http://keycloak:8080/auth/realms/proposta/protocol/openid-connect/certs

# Feign clients URL
feign:
  client:
    config:
      default:
        connection-timeout: 400
        read-timeout: 400
  servico:
    analise:
      api-solicitacao: http://analise:9999/api/solicitacao
    cartao:
      api-solicitacao: http://contas:8888/api/cartoes

# Scheduled
scheduled:
  periodicidade:
    executa-operacao: 30000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
        exclude: env,beans
    prometheus:
      enable: true
  metrics:
    tags:
      aplicacao: serviço de proposta
      ambiente: desenvolvimento
  endpoint:
    show-details: always