server:
  port: 8080
spring:
  application:
    name: proposta_api
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# Datasource - MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/proposta_api_db?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: password

# Key Cloack
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/proposta
          jwk-set-uri: http://localhost:18080/auth/realms/proposta/protocol/openid-connect/certs

# Feign clients URL
feign:
  client:
    config:
      default:
        connection-timeout: 400
        read-timeout: 400
  servico:
    analise:
      api-solicitacao: http://localhost:9999/api/solicitacao
    cartao:
      api-solicitacao: http://localhost:8888/api/cartoes

# Scheduled
scheduled:
  periodicidade:
    executa-operacao: 30000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
        exclude: env,beans
    prometheus:
      enable: true
  metrics:
    tags:
      aplicacao: serviço de proposta
      ambiente: desenvolvimento
  endpoint:
    show-details: always